# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Live' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Live
  pod 'JKSwiftExtension'
  # pod 'RxSwift'
  # pod 'RxCocoa'
  pod 'FDFullscreenPopGesture'
  pod 'MJRefresh'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod "ESTabBarController-swift"
end
